jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: npm install
        docker-image: node:22.14.0
        name: npm install
      - type: script
        script-content: |-
          npm install mocha-teamcity-reporter --no-save
          npm run test -- --reporter mocha-teamcity-reporter
        name: Tests (test.js)
        docker-image: node:22.14.0
