jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: npm install
        docker-image: node:22.14.0
        name: npm install
      - type: script
        script-content: npm test test.js
        name: Test
        docker-image: node:22.14.0
